[package]
name = "global-key-listener"
version = "0.1.0"
edition = "2021"

[dependencies]
rdev = { version = "0.4", features = ["unstable_grab"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
