services:
  ito-grpc-server:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run start
    container_name: ito-server
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: '3000'
      DB_HOST: localhost
      DB_PORT: '5432'
      DB_USER: devuser
      DB_PASS: devpass
      DB_NAME: devdb
  db:
    image: postgres:16
    container_name: ito-postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
