version: "3.8"

services:
  db:
    image: postgres:16
    container_name: ito-postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ..            
      dockerfile: Dockerfile 
      target: runner         
    container_name: ito-server
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"          
    environment:
      NODE_ENV: development
      PORT: "3000"
      DB_HOST: localhost
      DB_PORT: "5432"
      DB_USER: devuser
      DB_PASSWORD: devpass
      DB_NAME: devdb

volumes:
  pgdata: