name: Infra CDK

on:
  push:
    branches:
      - main
    paths:
      - 'server/infra/**'

permissions:
  contents: read
  id-token: write   # for OIDC

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout infra
        uses: actions/checkout@v3

      - name: Setup Node.js & CDK
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install infra dependencies
        working-directory: server/infra
        run: npm install

      - name: Verify CDK version
        working-directory: server/infra
        run: npx cdk --version

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::287641434880:role/ItoGitHubCiCdRole
          aws-region: us-west-2

      - name: Synthesize CDK template
        working-directory: server/infra
        run: npx cdk synth

      - name: Deploy to production
        working-directory: server/infra
        run: npx cdk deploy --all --require-approval never